# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexander Boest-Petersen
title: MSc in Geoinformatics Student
email: aboestpetersen@gmail.com
website: aboestpetersen.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  aboestpetersen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexanderboest-petersen
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  MSc in Technology student at Aalborg University in Geoinformatics & experienced Geographic Information Systems Analyst with a demonstrated history of working in the government administration industry. Proficient ESRI Desktop suite, ArcGIS Pro, ArcSDE, ArcGIS Online, AutoCAD, and SQL Server. Developed sUAS (Drone) program and policies from inception that is leveraged across an entire organization and transformed the capacity to provide GIS support across a city. Leveraged aerial data and machine learning processes to streamline workflows and increase efficiency. Built professional relationships with local airport administration while project managing and coordinating flights as well as post-flight data processing and map creation. Successfully applied for Part 107.39 (Flight Operations Over Non-Active Participants) waiver from the FAA whilst also being the first municipal government to be granted this waiver for mapping purposes. Experience with implementing and administering city-wide asset management software. Strong geography information systems professional with a Bachelor of Arts - BA focused in Geographic Information Systems from The University of Texas at Austin. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: City of Pflugerville
        link: pflugervilletx.gov
        # link_text: pflugervilletx.gov
        sub_title: GIS Intern
        caption: March 2018 - December 2018
        description: | # this will include new lines to allow paragraphs
            Gather and verify field information in support of department projects.
            Provide mapping and related documentation of assigned projects.
            Design maps for internal and external use.
            Provide assistance reviewing plats, zoning applications and site plan inspection.
            Assist with research and graphics related to demographics and other planning activities.
            Provide internal customer support.
            Scan and archive hardcopy information.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Aalborg University Copenhagen
        caption: 2020 - 2022
        sub_title: MSc in Geoinformatics
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Description.

      - layout: left
        title: The University of Texas at Austin
        caption: 2015 - 2018
        sub_title: BA Geography (Specialized in GIS)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Description.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in GIS and spatial data, some of my other interests and hobbies are:
      - Cooking
      - Learning
      - Motorsports
      - Reading
      - Aviation

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
